### ISSUE TITLE
unable to produce log file

### ISSUE THREAD

**Issue by jafar75** [alex-che/gcc-phases#1]
hello there, 

thanks for your script. I could not proper command to produce log file in CMake. I use `add_compile_options(-ftime-report)` in CMakeLists.txt, but i unable to produce log file. 
would you provide a small example?

thanks

**Comment by alex-che** [comment]
Hello jafar75,
are you using GCC as C++ compiler?
If yes, could you please post your CMakeLists.txt and an example log file?

**Comment by jafar75** [comment]
I think, i found the problem. using `add_compile_options(-H -ftime-report)`, i succeed to produce log file and using the script and reporting compilation time per unit. 
thanks,

**Comment by alex-che** [comment]
@jafar75 I'm glad you've figured it out. 

The reason was probably a copy-paste mistake in the corresponding part of the README file. I've just fixed it. 
Thanks!
